# Generated by Django 5.2.6 on 2025-10-01 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_cor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='eddereco',
            new_name='endereco',
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='cor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.cor'),
        ),
    ]
