# Generated by Django 5.2.6 on 2025-10-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_rename_eddereco_pedido_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_sessao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
