# Generated by Django 5.2.6 on 2025-10-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_cliente_id_sessao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
