# Generated by Django 5.2.6 on 2025-10-03 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_cidade_estado_alter_endereco_cidade_cidade_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
    ]
