# Generated by Django 5.2.6 on 2025-10-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_categoria_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
