# Generated by Django 5.2.6 on 2025-12-09 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0015_imagemproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemproduto',
            name='cor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.cor'),
        ),
    ]
