# Generated by Django 5.2.6 on 2026-03-26 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_imagemproduto_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_sessao',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='finalizado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='loja.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='loja.tipo'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='slug',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
